CREATE DATABASE ACADEMIA;
USE ACADEMIA;

CREATE TABLE ALUNOS (
    ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    CPF VARCHAR(14),
    EMAIL VARCHAR(100)
);

CREATE TABLE PLANOS (
    ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PLANO VARCHAR(50),
    VALOR DECIMAL(10,2)
);

CREATE TABLE MATRICULAS (
    ID_MATRICULAS INT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUNO INT,
    ID_PLANO INT,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO),
    FOREIGN KEY (ID_PLANO) REFERENCES PLANOS(ID_PLANO)
);

SHOW TABLES;
DESCRIBE ALUNOS;

INSERT INTO ALUNOS (NOME, CPF, EMAIL)
VALUES ('Carlos Silva', '111.111.111-11', 'carlos@email.com');

INSERT INTO PLANOS (NOME_PLANO, VALOR)
VALUES ('Mensal', '100.00');

INSERT INTO MATRICULAS (ID_ALUNO, ID_PLANO)
VALUES (1, 1);

SELECT * FROM ALUNOS;