CREATE DATABASE ACADEMIA;
USE ACADEMIA;

CREATE TABLE ALUNOS (
    ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    CPF VARCHAR(14),
    EMAIL VARCHAR(100)
);

CREATE TABLE PLANOS (
    ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PLANO VARCHAR(50),
    VALOR DECIMAL(10,2)
);

CREATE TABLE MATRICULAS (
    ID_MATRICULAS INT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUNO INT,
    ID_PLANO INT,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO),
    FOREIGN KEY (ID_PLANO) REFERENCES PLANOS(ID_PLANO)
);

SHOW TABLES;
DESCRIBE ALUNOS;

INSERT INTO ALUNOS (NOME, CPF, EMAIL)
VALUES ('Carlos Silva', '111.111.111-11', 'carlos@email.com');

INSERT INTO PLANOS (NOME_PLANO, VALOR)
VALUES ('Mensal', '100.00');

INSERT INTO MATRICULAS (ID_ALUNO, ID_PLANO)
VALUES (1, 1);

SELECT * FROM ALUNOS;

SELECT A.NOME, P.NOME_PLANO
FROM MATRICULAS M
JOIN ALUNOS A ON M.ID_ALUNO = A.ID_ALUNO
JOIN PLANOS P ON M.ID_PLANO = P.ID_PLANO;

SELECT NOME, EMAIL FROM ALUNOS;

SELECT * FROM ALUNOS WHERE ID_ALUNO = 1;

UPDATE ALUNOS
SET NOME = 'Carlos Oliveira'
WHERE ID_ALUNO = 1;

DELETE FROM MATRICULAS
WHERE ID_MATRICULAS = 1;

-- DROP TABLE MATRICULAS;
-- DROP TABLE ALUNOS;
-- DROP TABLE PLANOS;

INSERT INTO ALUNOS (NOME, CPF, EMAIL)
VALUES ('Davi Robson', '222.222.222-22', 'davi@email.com');

INSERT INTO PLANOS (NOME_PLANO, VALOR)
VALUES ('Anual', '999.00');

INSERT INTO MATRICULAS (ID_ALUNO, ID_PLANO)
VALUES (2, 2);

UPDATE ALUNOS
SET NOME = 'Davi Carvalho'
WHERE ID_ALUNO = 2;