CREATE DATABASE BARBEARIA;
USE BARBEARIA;

CREATE TABLE CLIENTE(
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    -- PRINCIPAL
    NOME VARCHAR(100) UNIQUE NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    GENERO CHAR(1),
    -- CONTATO
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    -- ENDERECO
    ENDERECO VARCHAR(2),
    NUMERO VARCHAR(10),
    TIPO_RESIDENCIA(10),
    CEP VARCHAR(10)
);

CREATE TABLE SERVICO(
    ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
    -- PRINCIPAL
    NOME_SERVICO VARCHAR(100)
);

CREATE TABLE BARBEIRO(
    ID_BARBEIRO INT AUTO_INCREMENT PRIMARY KEY,
    -- PRINCIPAL
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    -- CONTATO
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100) UNIQUE
);

